// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./database/models.js";

/**
 * StartSessionRequest represents the parameters for starting a new terminal session
 */
export class StartSessionRequest {
    /**
     * Creates a new StartSessionRequest instance.
     * @param {Partial<StartSessionRequest>} [$$source = {}] - The source object to create the StartSessionRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sessionType" in $$source)) {
            /**
             * bash, zsh, fish, pwsh, git-bash, custom
             * @member
             * @type {string}
             */
            this["sessionType"] = "";
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["config"] = {};
        }
        if (!("cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartSessionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartSessionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new StartSessionRequest(/** @type {Partial<StartSessionRequest>} */($$parsedSource));
    }
}

/**
 * TreeNode represents a node in the hierarchical session tree
 */
export class TreeNode {
    /**
     * Creates a new TreeNode instance.
     * @param {Partial<TreeNode>} [$$source = {}] - The source object to create the TreeNode.
     */
    constructor($$source = {}) {
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {database$0.SessionNode}
             */
            this["session"] = (new database$0.SessionNode());
        }
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {TreeNode[]}
             */
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TreeNode}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField1_0($$parsedSource["children"]);
        }
        return new TreeNode(/** @type {Partial<TreeNode>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = database$0.SessionNode.createFrom;
const $$createType2 = TreeNode.createFrom;
const $$createType3 = $Create.Array($$createType2);
