// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../golang.org/x/crypto/ssh/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../io/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as os$0 from "../os/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exec$0 from "../os/exec/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./database/models.js";

export class FileEntry {
    "name": string;
    "path": string;
    "size": number;
    "mode": string;
    "isDir": boolean;
    "modTime": number;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export class FileList {
    "remote_path": string;
    "files": FileEntry[];

    /** Creates a new FileList instance. */
    constructor($$source: Partial<FileList> = {}) {
        if (!("remote_path" in $$source)) {
            this["remote_path"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileList instance from a string or object.
     */
    static createFrom($$source: any = {}): FileList {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new FileList($$parsedSource as Partial<FileList>);
    }
}

export class RecordingOptions {
    "SessionID": string;
    "SessionName": string;
    "SessionType": string;
    "Cols": number;
    "Rows": number;
    "CaptureInput": boolean;
    "Encrypt": boolean;

    /**
     * used to derive master key via Argon2
     */
    "Passphrase": string;

    /** Creates a new RecordingOptions instance. */
    constructor($$source: Partial<RecordingOptions> = {}) {
        if (!("SessionID" in $$source)) {
            this["SessionID"] = "";
        }
        if (!("SessionName" in $$source)) {
            this["SessionName"] = "";
        }
        if (!("SessionType" in $$source)) {
            this["SessionType"] = "";
        }
        if (!("Cols" in $$source)) {
            this["Cols"] = 0;
        }
        if (!("Rows" in $$source)) {
            this["Rows"] = 0;
        }
        if (!("CaptureInput" in $$source)) {
            this["CaptureInput"] = false;
        }
        if (!("Encrypt" in $$source)) {
            this["Encrypt"] = false;
        }
        if (!("Passphrase" in $$source)) {
            this["Passphrase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordingOptions($$parsedSource as Partial<RecordingOptions>);
    }
}

/**
 * StartSessionRequest represents the parameters for starting a new terminal session
 */
export class StartSessionRequest {
    "id": string;

    /**
     * bash, zsh, fish, pwsh, git-bash, custom
     */
    "sessionType": string;
    "config": { [_: string]: string };
    "cols": number;
    "rows": number;

    /** Creates a new StartSessionRequest instance. */
    constructor($$source: Partial<StartSessionRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionType" in $$source)) {
            this["sessionType"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartSessionRequest {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new StartSessionRequest($$parsedSource as Partial<StartSessionRequest>);
    }
}

/**
 * SystemStats represents current system resource usage
 */
export class SystemStats {
    "cpuPercent": number;
    "memoryPercent": number;
    "memoryUsed": number;
    "memoryTotal": number;
    "diskPercent": number;
    "diskUsed": number;
    "diskTotal": number;
    "networkSent": number;
    "networkRecv": number;
    "loadAvg1": number;
    "loadAvg5": number;
    "loadAvg15": number;

    /** Creates a new SystemStats instance. */
    constructor($$source: Partial<SystemStats> = {}) {
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("memoryPercent" in $$source)) {
            this["memoryPercent"] = 0;
        }
        if (!("memoryUsed" in $$source)) {
            this["memoryUsed"] = 0;
        }
        if (!("memoryTotal" in $$source)) {
            this["memoryTotal"] = 0;
        }
        if (!("diskPercent" in $$source)) {
            this["diskPercent"] = 0;
        }
        if (!("diskUsed" in $$source)) {
            this["diskUsed"] = 0;
        }
        if (!("diskTotal" in $$source)) {
            this["diskTotal"] = 0;
        }
        if (!("networkSent" in $$source)) {
            this["networkSent"] = 0;
        }
        if (!("networkRecv" in $$source)) {
            this["networkRecv"] = 0;
        }
        if (!("loadAvg1" in $$source)) {
            this["loadAvg1"] = 0;
        }
        if (!("loadAvg5" in $$source)) {
            this["loadAvg5"] = 0;
        }
        if (!("loadAvg15" in $$source)) {
            this["loadAvg15"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemStats($$parsedSource as Partial<SystemStats>);
    }
}

export class TerminalColors {
    "background": string;
    "foreground": string;
    "cursor": string;
    "selectionBackground": string;
    "black": string;
    "red": string;
    "green": string;
    "yellow": string;
    "blue": string;
    "magenta": string;
    "cyan": string;
    "white": string;
    "brightBlack": string;
    "brightRed": string;
    "brightGreen": string;
    "brightYellow": string;
    "brightBlue": string;
    "brightMagenta": string;
    "brightCyan": string;
    "brightWhite": string;

    /** Creates a new TerminalColors instance. */
    constructor($$source: Partial<TerminalColors> = {}) {
        if (!("background" in $$source)) {
            this["background"] = "";
        }
        if (!("foreground" in $$source)) {
            this["foreground"] = "";
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = "";
        }
        if (!("selectionBackground" in $$source)) {
            this["selectionBackground"] = "";
        }
        if (!("black" in $$source)) {
            this["black"] = "";
        }
        if (!("red" in $$source)) {
            this["red"] = "";
        }
        if (!("green" in $$source)) {
            this["green"] = "";
        }
        if (!("yellow" in $$source)) {
            this["yellow"] = "";
        }
        if (!("blue" in $$source)) {
            this["blue"] = "";
        }
        if (!("magenta" in $$source)) {
            this["magenta"] = "";
        }
        if (!("cyan" in $$source)) {
            this["cyan"] = "";
        }
        if (!("white" in $$source)) {
            this["white"] = "";
        }
        if (!("brightBlack" in $$source)) {
            this["brightBlack"] = "";
        }
        if (!("brightRed" in $$source)) {
            this["brightRed"] = "";
        }
        if (!("brightGreen" in $$source)) {
            this["brightGreen"] = "";
        }
        if (!("brightYellow" in $$source)) {
            this["brightYellow"] = "";
        }
        if (!("brightBlue" in $$source)) {
            this["brightBlue"] = "";
        }
        if (!("brightMagenta" in $$source)) {
            this["brightMagenta"] = "";
        }
        if (!("brightCyan" in $$source)) {
            this["brightCyan"] = "";
        }
        if (!("brightWhite" in $$source)) {
            this["brightWhite"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalColors instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalColors {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalColors($$parsedSource as Partial<TerminalColors>);
    }
}

export class TerminalSession {
    "ID": string;
    "PTY": os$0.File | null;
    "Cmd": exec$0.Cmd | null;
    "Running": boolean;

    /**
     * SSH-specific fields
     */
    "SSHClient": ssh$0.Client | null;
    "SSHSession": ssh$0.Session | null;
    "SSHStdin": io$0.WriteCloser;
    "IsSSH": boolean;

    /**
     * Windows/Pipe fallback fields (non-PTY local sessions on Windows)
     */
    "Stdin": io$0.WriteCloser;
    "Stdout": io$0.Reader;
    "Stderr": io$0.Reader;

    /**
     * Optional PTY resizer for platform-specific implementations
     */
    "ResizePTY": any;

    /**
     * Process control for platforms that don't use exec.Cmd
     */
    "Wait": any;
    "Kill": any;
    "ClosePTY": any;

    /** Creates a new TerminalSession instance. */
    constructor($$source: Partial<TerminalSession> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("PTY" in $$source)) {
            this["PTY"] = null;
        }
        if (!("Cmd" in $$source)) {
            this["Cmd"] = null;
        }
        if (!("Running" in $$source)) {
            this["Running"] = false;
        }
        if (!("SSHClient" in $$source)) {
            this["SSHClient"] = null;
        }
        if (!("SSHSession" in $$source)) {
            this["SSHSession"] = null;
        }
        if (!("SSHStdin" in $$source)) {
            this["SSHStdin"] = null;
        }
        if (!("IsSSH" in $$source)) {
            this["IsSSH"] = false;
        }
        if (!("Stdin" in $$source)) {
            this["Stdin"] = null;
        }
        if (!("Stdout" in $$source)) {
            this["Stdout"] = null;
        }
        if (!("Stderr" in $$source)) {
            this["Stderr"] = null;
        }
        if (!("ResizePTY" in $$source)) {
            this["ResizePTY"] = null;
        }
        if (!("Wait" in $$source)) {
            this["Wait"] = null;
        }
        if (!("Kill" in $$source)) {
            this["Kill"] = null;
        }
        if (!("ClosePTY" in $$source)) {
            this["ClosePTY"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSession instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalSession {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        const $$createField4_0 = $$createType8;
        const $$createField5_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PTY" in $$parsedSource) {
            $$parsedSource["PTY"] = $$createField1_0($$parsedSource["PTY"]);
        }
        if ("Cmd" in $$parsedSource) {
            $$parsedSource["Cmd"] = $$createField2_0($$parsedSource["Cmd"]);
        }
        if ("SSHClient" in $$parsedSource) {
            $$parsedSource["SSHClient"] = $$createField4_0($$parsedSource["SSHClient"]);
        }
        if ("SSHSession" in $$parsedSource) {
            $$parsedSource["SSHSession"] = $$createField5_0($$parsedSource["SSHSession"]);
        }
        return new TerminalSession($$parsedSource as Partial<TerminalSession>);
    }
}

export class Theme {
    "name": string;
    "id": string;

    /**
     * "dark" or "light"
     */
    "type": string;
    "colors": ThemeColors;
    "terminal": TerminalColors;

    /** Creates a new Theme instance. */
    constructor($$source: Partial<Theme> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("colors" in $$source)) {
            this["colors"] = (new ThemeColors());
        }
        if (!("terminal" in $$source)) {
            this["terminal"] = (new TerminalColors());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     */
    static createFrom($$source: any = {}): Theme {
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField3_0($$parsedSource["colors"]);
        }
        if ("terminal" in $$parsedSource) {
            $$parsedSource["terminal"] = $$createField4_0($$parsedSource["terminal"]);
        }
        return new Theme($$parsedSource as Partial<Theme>);
    }
}

export class ThemeColors {
    "bg": {"primary": string, "secondary": string, "tertiary": string, "quaternary": string};
    "text": {"primary": string, "secondary": string, "muted": string};
    "accent": {"blue": string, "green": string, "red": string, "yellow": string, "purple": string, "pink": string, "cyan": string, "orange": string};
    "border": string;
    "hover": string;
    "active": string;
    "selection": string;

    /** Creates a new ThemeColors instance. */
    constructor($$source: Partial<ThemeColors> = {}) {
        if (!("bg" in $$source)) {
            this["bg"] = {"primary": "", "secondary": "", "tertiary": "", "quaternary": ""};
        }
        if (!("text" in $$source)) {
            this["text"] = {"primary": "", "secondary": "", "muted": ""};
        }
        if (!("accent" in $$source)) {
            this["accent"] = {"blue": "", "green": "", "red": "", "yellow": "", "purple": "", "pink": "", "cyan": "", "orange": ""};
        }
        if (!("border" in $$source)) {
            this["border"] = "";
        }
        if (!("hover" in $$source)) {
            this["hover"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = "";
        }
        if (!("selection" in $$source)) {
            this["selection"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeColors instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeColors {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeColors($$parsedSource as Partial<ThemeColors>);
    }
}

/**
 * TreeNode represents a node in the hierarchical session tree
 */
export class TreeNode {
    "session": database$0.SessionNode;
    "children": TreeNode[];

    /** Creates a new TreeNode instance. */
    constructor($$source: Partial<TreeNode> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new database$0.SessionNode());
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TreeNode {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField1_0($$parsedSource["children"]);
        }
        return new TreeNode($$parsedSource as Partial<TreeNode>);
    }
}

// Private type creation functions
const $$createType0 = FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = os$0.File.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = exec$0.Cmd.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = ssh$0.Client.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = ssh$0.Session.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = ThemeColors.createFrom;
const $$createType12 = TerminalColors.createFrom;
const $$createType13 = database$0.SessionNode.createFrom;
const $$createType14 = TreeNode.createFrom;
const $$createType15 = $Create.Array($$createType14);
