// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./database/models.js";

/**
 * StartSessionRequest represents the parameters for starting a new terminal session
 */
export class StartSessionRequest {
    "id": string;

    /**
     * bash, zsh, fish, pwsh, git-bash, custom
     */
    "sessionType": string;
    "config": { [_: string]: string };
    "cols": number;
    "rows": number;

    /** Creates a new StartSessionRequest instance. */
    constructor($$source: Partial<StartSessionRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionType" in $$source)) {
            this["sessionType"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartSessionRequest {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new StartSessionRequest($$parsedSource as Partial<StartSessionRequest>);
    }
}

/**
 * TreeNode represents a node in the hierarchical session tree
 */
export class TreeNode {
    "session": database$0.SessionNode;
    "children": TreeNode[];

    /** Creates a new TreeNode instance. */
    constructor($$source: Partial<TreeNode> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new database$0.SessionNode());
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TreeNode {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField1_0($$parsedSource["children"]);
        }
        return new TreeNode($$parsedSource as Partial<TreeNode>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = database$0.SessionNode.createFrom;
const $$createType2 = TreeNode.createFrom;
const $$createType3 = $Create.Array($$createType2);
