// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../golang.org/x/crypto/ssh/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../io/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as os$0 from "../os/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exec$0 from "../os/exec/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./database/models.js";

/**
 * StartSessionRequest represents the parameters for starting a new terminal session
 */
export class StartSessionRequest {
    "id": string;

    /**
     * bash, zsh, fish, pwsh, git-bash, custom
     */
    "sessionType": string;
    "config": { [_: string]: string };
    "cols": number;
    "rows": number;

    /** Creates a new StartSessionRequest instance. */
    constructor($$source: Partial<StartSessionRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionType" in $$source)) {
            this["sessionType"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartSessionRequest {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new StartSessionRequest($$parsedSource as Partial<StartSessionRequest>);
    }
}

/**
 * SystemStats represents current system resource usage
 */
export class SystemStats {
    "cpuPercent": number;
    "memoryPercent": number;
    "memoryUsed": number;
    "memoryTotal": number;
    "diskPercent": number;
    "diskUsed": number;
    "diskTotal": number;
    "networkSent": number;
    "networkRecv": number;
    "loadAvg1": number;
    "loadAvg5": number;
    "loadAvg15": number;

    /** Creates a new SystemStats instance. */
    constructor($$source: Partial<SystemStats> = {}) {
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("memoryPercent" in $$source)) {
            this["memoryPercent"] = 0;
        }
        if (!("memoryUsed" in $$source)) {
            this["memoryUsed"] = 0;
        }
        if (!("memoryTotal" in $$source)) {
            this["memoryTotal"] = 0;
        }
        if (!("diskPercent" in $$source)) {
            this["diskPercent"] = 0;
        }
        if (!("diskUsed" in $$source)) {
            this["diskUsed"] = 0;
        }
        if (!("diskTotal" in $$source)) {
            this["diskTotal"] = 0;
        }
        if (!("networkSent" in $$source)) {
            this["networkSent"] = 0;
        }
        if (!("networkRecv" in $$source)) {
            this["networkRecv"] = 0;
        }
        if (!("loadAvg1" in $$source)) {
            this["loadAvg1"] = 0;
        }
        if (!("loadAvg5" in $$source)) {
            this["loadAvg5"] = 0;
        }
        if (!("loadAvg15" in $$source)) {
            this["loadAvg15"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemStats($$parsedSource as Partial<SystemStats>);
    }
}

export class TerminalSession {
    "ID": string;
    "PTY": os$0.File | null;
    "Cmd": exec$0.Cmd | null;
    "Running": boolean;

    /**
     * SSH-specific fields
     */
    "SSHClient": ssh$0.Client | null;
    "SSHSession": ssh$0.Session | null;
    "SSHStdin": io$0.WriteCloser;
    "IsSSH": boolean;

    /** Creates a new TerminalSession instance. */
    constructor($$source: Partial<TerminalSession> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("PTY" in $$source)) {
            this["PTY"] = null;
        }
        if (!("Cmd" in $$source)) {
            this["Cmd"] = null;
        }
        if (!("Running" in $$source)) {
            this["Running"] = false;
        }
        if (!("SSHClient" in $$source)) {
            this["SSHClient"] = null;
        }
        if (!("SSHSession" in $$source)) {
            this["SSHSession"] = null;
        }
        if (!("SSHStdin" in $$source)) {
            this["SSHStdin"] = null;
        }
        if (!("IsSSH" in $$source)) {
            this["IsSSH"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSession instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalSession {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PTY" in $$parsedSource) {
            $$parsedSource["PTY"] = $$createField1_0($$parsedSource["PTY"]);
        }
        if ("Cmd" in $$parsedSource) {
            $$parsedSource["Cmd"] = $$createField2_0($$parsedSource["Cmd"]);
        }
        if ("SSHClient" in $$parsedSource) {
            $$parsedSource["SSHClient"] = $$createField4_0($$parsedSource["SSHClient"]);
        }
        if ("SSHSession" in $$parsedSource) {
            $$parsedSource["SSHSession"] = $$createField5_0($$parsedSource["SSHSession"]);
        }
        return new TerminalSession($$parsedSource as Partial<TerminalSession>);
    }
}

/**
 * TreeNode represents a node in the hierarchical session tree
 */
export class TreeNode {
    "session": database$0.SessionNode;
    "children": TreeNode[];

    /** Creates a new TreeNode instance. */
    constructor($$source: Partial<TreeNode> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new database$0.SessionNode());
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TreeNode {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField1_0($$parsedSource["children"]);
        }
        return new TreeNode($$parsedSource as Partial<TreeNode>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = os$0.File.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = exec$0.Cmd.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ssh$0.Client.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = ssh$0.Session.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = database$0.SessionNode.createFrom;
const $$createType10 = TreeNode.createFrom;
const $$createType11 = $Create.Array($$createType10);
