// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppendInput(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(569452402, sessionID, data);
}

export function AppendOutput(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(479956455, sessionID, data);
}

export function AppendResize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(277338562, sessionID, cols, rows);
}

export function Start(opts: $models.RecordingOptions): $CancellablePromise<void> {
    return $Call.ByID(3617325250, opts);
}

export function Stop(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2647128898, sessionID);
}
