// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RemoteStatsService monitors remote SSH server statistics
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * SetActiveSession sets which session to monitor (called from frontend)
 */
export function SetActiveSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(643824766, sessionID);
}

/**
 * SetApp sets the Wails application instance
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(735355355, app);
}

/**
 * Start begins collecting remote stats
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1128591068);
}

/**
 * Stop stops the stats collection
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(843293304);
}
