// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./database/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSession creates a new session node
 */
export function CreateSession(session: database$0.SessionNode): $CancellablePromise<void> {
    return $Call.ByID(4095665835, session);
}

/**
 * DeleteSession deletes a session
 */
export function DeleteSession(id: string, cascade: boolean): $CancellablePromise<void> {
    return $Call.ByID(2329038450, id, cascade);
}

/**
 * DeleteSessionConfig deletes a config key
 */
export function DeleteSessionConfig(sessionID: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(542344188, sessionID, key);
}

/**
 * DuplicateSession creates a copy of a session with a new ID
 */
export function DuplicateSession(id: string, newID: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(352638846, id, newID, newName);
}

/**
 * GetAllSessions retrieves all session nodes
 */
export function GetAllSessions(): $CancellablePromise<database$0.SessionNode[]> {
    return $Call.ByID(1467064435).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetEffectiveConfig gets the effective configuration with inheritance
 */
export function GetEffectiveConfig(sessionID: string): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(2008311378, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSession retrieves a single session by ID
 */
export function GetSession(id: string): $CancellablePromise<database$0.SessionNode | null> {
    return $Call.ByID(4260590885, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSessionConfig retrieves all direct configs for a session (not inherited)
 */
export function GetSessionConfig(sessionID: string): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(2952522247, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSessionTree builds a hierarchical tree structure from flat session list
 */
export function GetSessionTree(): $CancellablePromise<$models.TreeNode[]> {
    return $Call.ByID(3075482901).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * MoveSession moves a session to a new parent and position
 */
export function MoveSession(sessionID: string, newParentID: string | null, newPosition: number): $CancellablePromise<void> {
    return $Call.ByID(567945252, sessionID, newParentID, newPosition);
}

/**
 * SetSessionConfig sets a config value for a session
 */
export function SetSessionConfig(sessionID: string, key: string, value: string, valueType: string): $CancellablePromise<void> {
    return $Call.ByID(1147065995, sessionID, key, value, valueType);
}

/**
 * UpdateSession updates an existing session
 */
export function UpdateSession(session: database$0.SessionNode): $CancellablePromise<void> {
    return $Call.ByID(2044200324, session);
}

// Private type creation functions
const $$createType0 = database$0.SessionNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = $models.TreeNode.createFrom;
const $$createType5 = $Create.Array($$createType4);
