// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./database/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSession creates a new session node
 * @param {database$0.SessionNode} session
 * @returns {$CancellablePromise<void>}
 */
export function CreateSession(session) {
    return $Call.ByID(4095665835, session);
}

/**
 * DeleteSession deletes a session
 * @param {string} id
 * @param {boolean} cascade
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(id, cascade) {
    return $Call.ByID(2329038450, id, cascade);
}

/**
 * DeleteSessionConfig deletes a config key
 * @param {string} sessionID
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSessionConfig(sessionID, key) {
    return $Call.ByID(542344188, sessionID, key);
}

/**
 * DuplicateSession creates a copy of a session with a new ID
 * @param {string} id
 * @param {string} newID
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function DuplicateSession(id, newID, newName) {
    return $Call.ByID(352638846, id, newID, newName);
}

/**
 * GetAllSessions retrieves all session nodes
 * @returns {$CancellablePromise<database$0.SessionNode[]>}
 */
export function GetAllSessions() {
    return $Call.ByID(1467064435).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetEffectiveConfig gets the effective configuration with inheritance
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetEffectiveConfig(sessionID) {
    return $Call.ByID(2008311378, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSession retrieves a single session by ID
 * @param {string} id
 * @returns {$CancellablePromise<database$0.SessionNode | null>}
 */
export function GetSession(id) {
    return $Call.ByID(4260590885, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetSessionConfig retrieves all direct configs for a session (not inherited)
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetSessionConfig(sessionID) {
    return $Call.ByID(2952522247, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSessionTree builds a hierarchical tree structure from flat session list
 * @returns {$CancellablePromise<$models.TreeNode[]>}
 */
export function GetSessionTree() {
    return $Call.ByID(3075482901).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * MoveSession moves a session to a new parent and position
 * @param {string} sessionID
 * @param {string | null} newParentID
 * @param {number} newPosition
 * @returns {$CancellablePromise<void>}
 */
export function MoveSession(sessionID, newParentID, newPosition) {
    return $Call.ByID(567945252, sessionID, newParentID, newPosition);
}

/**
 * SetSessionConfig sets a config value for a session
 * @param {string} sessionID
 * @param {string} key
 * @param {string} value
 * @param {string} valueType
 * @returns {$CancellablePromise<void>}
 */
export function SetSessionConfig(sessionID, key, value, valueType) {
    return $Call.ByID(1147065995, sessionID, key, value, valueType);
}

/**
 * UpdateSession updates an existing session
 * @param {database$0.SessionNode} session
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSession(session) {
    return $Call.ByID(2044200324, session);
}

// Private type creation functions
const $$createType0 = database$0.SessionNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = $models.TreeNode.createFrom;
const $$createType5 = $Create.Array($$createType4);
