// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./database/models.js";

/**
 * GetAllSettings retrieves all settings as a map
 */
export function GetAllSettings(): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(2239270486).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAutoLaunch retrieves the auto-launch setting
 */
export function GetAutoLaunch(): $CancellablePromise<string> {
    return $Call.ByID(4190359040);
}

/**
 * GetConfirmTabClose retrieves the confirm tab close setting
 */
export function GetConfirmTabClose(): $CancellablePromise<string> {
    return $Call.ByID(389550477);
}

/**
 * GetFontFamily retrieves the font family setting
 */
export function GetFontFamily(): $CancellablePromise<string> {
    return $Call.ByID(2852316217);
}

/**
 * GetFontSize retrieves the font size setting
 */
export function GetFontSize(): $CancellablePromise<string> {
    return $Call.ByID(4260979468);
}

/**
 * GetRestoreTabsOnStartup retrieves the restore tabs on startup setting
 */
export function GetRestoreTabsOnStartup(): $CancellablePromise<string> {
    return $Call.ByID(1139087256);
}

/**
 * GetSetting retrieves a single setting
 */
export function GetSetting(key: string): $CancellablePromise<database$0.Setting | null> {
    return $Call.ByID(2897416356, key).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetTabSnapshots retrieves the saved tab snapshots
 */
export function GetTabSnapshots(): $CancellablePromise<string> {
    return $Call.ByID(527777620);
}

/**
 * GetTheme retrieves the current theme setting
 */
export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(1377976733);
}

/**
 * SaveTabSnapshots saves the current tab snapshots
 */
export function SaveTabSnapshots(snapshots: string): $CancellablePromise<void> {
    return $Call.ByID(2314107493, snapshots);
}

/**
 * SetAutoLaunch updates the auto-launch setting
 */
export function SetAutoLaunch(autoLaunch: string): $CancellablePromise<void> {
    return $Call.ByID(3703829852, autoLaunch);
}

/**
 * SetConfirmTabClose updates the confirm tab close setting
 */
export function SetConfirmTabClose(confirm: string): $CancellablePromise<void> {
    return $Call.ByID(2534052209, confirm);
}

/**
 * SetFontFamily updates the font family setting
 */
export function SetFontFamily(fontFamily: string): $CancellablePromise<void> {
    return $Call.ByID(3000117645, fontFamily);
}

/**
 * SetFontSize updates the font size setting
 */
export function SetFontSize(fontSize: string): $CancellablePromise<void> {
    return $Call.ByID(2771488912, fontSize);
}

/**
 * SetRestoreTabsOnStartup updates the restore tabs on startup setting
 */
export function SetRestoreTabsOnStartup(restore: string): $CancellablePromise<void> {
    return $Call.ByID(3583864564, restore);
}

/**
 * SetSetting sets or updates a setting
 */
export function SetSetting(key: string, value: string, valueType: string): $CancellablePromise<void> {
    return $Call.ByID(512149104, key, value, valueType);
}

/**
 * SetTheme updates the theme setting
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(466396097, theme);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = database$0.Setting.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
