// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./database/models.js";

/**
 * GetAllSettings retrieves all settings as a map
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetAllSettings() {
    return $Call.ByID(2239270486).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAutoLaunch retrieves the auto-launch setting
 * @returns {$CancellablePromise<string>}
 */
export function GetAutoLaunch() {
    return $Call.ByID(4190359040);
}

/**
 * GetFontFamily retrieves the font family setting
 * @returns {$CancellablePromise<string>}
 */
export function GetFontFamily() {
    return $Call.ByID(2852316217);
}

/**
 * GetFontSize retrieves the font size setting
 * @returns {$CancellablePromise<string>}
 */
export function GetFontSize() {
    return $Call.ByID(4260979468);
}

/**
 * GetSetting retrieves a single setting
 * @param {string} key
 * @returns {$CancellablePromise<database$0.Setting | null>}
 */
export function GetSetting(key) {
    return $Call.ByID(2897416356, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetTabSnapshots retrieves the saved tab snapshots
 * @returns {$CancellablePromise<string>}
 */
export function GetTabSnapshots() {
    return $Call.ByID(527777620);
}

/**
 * GetTheme retrieves the current theme setting
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(1377976733);
}

/**
 * SaveTabSnapshots saves the current tab snapshots
 * @param {string} snapshots
 * @returns {$CancellablePromise<void>}
 */
export function SaveTabSnapshots(snapshots) {
    return $Call.ByID(2314107493, snapshots);
}

/**
 * SetAutoLaunch updates the auto-launch setting
 * @param {string} autoLaunch
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoLaunch(autoLaunch) {
    return $Call.ByID(3703829852, autoLaunch);
}

/**
 * SetFontFamily updates the font family setting
 * @param {string} fontFamily
 * @returns {$CancellablePromise<void>}
 */
export function SetFontFamily(fontFamily) {
    return $Call.ByID(3000117645, fontFamily);
}

/**
 * SetFontSize updates the font size setting
 * @param {string} fontSize
 * @returns {$CancellablePromise<void>}
 */
export function SetFontSize(fontSize) {
    return $Call.ByID(2771488912, fontSize);
}

/**
 * SetSetting sets or updates a setting
 * @param {string} key
 * @param {string} value
 * @param {string} valueType
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value, valueType) {
    return $Call.ByID(512149104, key, value, valueType);
}

/**
 * SetTheme updates the theme setting
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(466396097, theme);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = database$0.Setting.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
