// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function HandleSSHFSDelete(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3253392308, sessionID, path);
}

export function HandleSSHFSDownload(sessionID: string, remotePath: string, dest: string): $CancellablePromise<void> {
    return $Call.ByID(685372339, sessionID, remotePath, dest);
}

export function HandleSSHFSDownloadDir(sessionID: string, remotePath: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(991661298, sessionID, remotePath, localPath);
}

export function HandleSSHFSList(sessionID: string, remotePath: string): $CancellablePromise<$models.FileList> {
    return $Call.ByID(2405997583, sessionID, remotePath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function HandleSSHFSMkdir(sessionID: string, remotePath: string, recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(4134140462, sessionID, remotePath, recursive);
}

export function HandleSSHFSRename(sessionID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(1829581277, sessionID, oldPath, newPath);
}

export function HandleSSHFSSave(sessionID: string, remotePath: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(763328818, sessionID, remotePath, destPath);
}

export function HandleSSHFSSaveDir(sessionID: string, remotePath: string, dest: string): $CancellablePromise<void> {
    return $Call.ByID(3524342905, sessionID, remotePath, dest);
}

export function HandleSSHFSUpload(sessionID: string, localPath: string, destDir: string, jobID: string): $CancellablePromise<void> {
    return $Call.ByID(2079443594, sessionID, localPath, destDir, jobID);
}

// Private type creation functions
const $$createType0 = $models.FileList.createFrom;
