// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemStatsService provides system resource monitoring
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetCurrentStats returns the current system stats (for on-demand requests)
 */
export function GetCurrentStats(): $CancellablePromise<$models.SystemStats> {
    return $Call.ByID(3896185695).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp sets the Wails application instance
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4059937514, app);
}

/**
 * Start begins collecting and emitting system stats
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2075012907);
}

/**
 * Stop stops the stats collection
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3054454425);
}

// Private type creation functions
const $$createType0 = $models.SystemStats.createFrom;
