// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseSession closes a terminal session
 */
export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3305403653, id);
}

/**
 * GetActiveSessions returns a list of active session IDs
 */
export function GetActiveSessions(): $CancellablePromise<string[]> {
    return $Call.ByID(712451168).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsSessionRunning checks if a session is still running
 */
export function IsSessionRunning(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(4072388606, id);
}

/**
 * ResizeSession resizes a terminal session
 */
export function ResizeSession(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1276344907, id, cols, rows);
}

/**
 * StartSession starts a new terminal session
 */
export function StartSession(req: $models.StartSessionRequest): $CancellablePromise<void> {
    return $Call.ByID(2881274561, req);
}

/**
 * WriteToSession writes data to a terminal session
 */
export function WriteToSession(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2568628319, id, data);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
