// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseSession closes a terminal session
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(id) {
    return $Call.ByID(3305403653, id);
}

/**
 * GetActiveSessions returns a list of active session IDs
 * @returns {$CancellablePromise<string[]>}
 */
export function GetActiveSessions() {
    return $Call.ByID(712451168).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * IsSessionRunning checks if a session is still running
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSessionRunning(id) {
    return $Call.ByID(4072388606, id);
}

/**
 * ResizeSession resizes a terminal session
 * @param {string} id
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeSession(id, cols, rows) {
    return $Call.ByID(1276344907, id, cols, rows);
}

/**
 * StartSession starts a new terminal session
 * @param {$models.StartSessionRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function StartSession(req) {
    return $Call.ByID(2881274561, req);
}

/**
 * WriteToSession writes data to a terminal session
 * @param {string} id
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteToSession(id, data) {
    return $Call.ByID(2568628319, id, data);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
