// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportTheme exports a theme to a JSON file
 */
export function ExportTheme(id: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(857476231, id, destPath);
}

/**
 * GetActiveTheme returns the currently active theme
 */
export function GetActiveTheme(): $CancellablePromise<$models.Theme | null> {
    return $Call.ByID(2081604447).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAllThemes returns all available themes (built-in + user)
 */
export function GetAllThemes(): $CancellablePromise<$models.Theme[]> {
    return $Call.ByID(1579527609).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetTheme returns a specific theme by ID
 */
export function GetTheme(id: string): $CancellablePromise<$models.Theme | null> {
    return $Call.ByID(3482301073, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportTheme imports a theme from a JSON file
 */
export function ImportTheme(sourcePath: string): $CancellablePromise<void> {
    return $Call.ByID(1339812306, sourcePath);
}

/**
 * SetActiveTheme sets the active theme
 */
export function SetActiveTheme(id: string): $CancellablePromise<void> {
    return $Call.ByID(712960643, id);
}

// Private type creation functions
const $$createType0 = $models.Theme.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
