//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../term/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "recording:delete": $$createType0,
        "recording:list": $$createType0,
        "recording:list:error": $$createType0,
        "recording:list:request": $$createType0,
        "recording:replay:ended": $$createType0,
        "recording:replay:header": $$createType0,
        "recording:replay:output": $$createType0,
        "recording:replay:resize": $$createType0,
        "recording:replay:start": $$createType0,
        "recording:replay:stop": $$createType0,
        "recording:start": $$createType0,
        "recording:started": $$createType0,
        "recording:stop": $$createType0,
        "recording:stopped": $$createType0,
        "ssh:hostkey_prompt": $$createType0,
        "ssh:hostkey_response": $$createType0,
        "ssh:known_hosts:delete": $$createType0,
        "ssh:known_hosts:list": $$createType0,
        "ssh:known_hosts:list:request": $$createType0,
        "system:stats": $$createType1,
        "terminal:data": $$createType0,
        "terminal:error": $$createType0,
        "terminal:exit": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = main$0.SystemStats.createFrom;

configure();
