//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../term/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "system:stats": $$createType0,
        "terminal:data": $$createType1,
        "terminal:error": $$createType1,
        "terminal:exit": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = main$0.SystemStats.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);

configure();
