// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../term/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "recording:delete": { [_: string]: any };
            "recording:list": { [_: string]: any };
            "recording:list:error": { [_: string]: any };
            "recording:list:request": { [_: string]: any };
            "recording:replay:ended": { [_: string]: any };
            "recording:replay:header": { [_: string]: any };
            "recording:replay:output": { [_: string]: any };
            "recording:replay:resize": { [_: string]: any };
            "recording:replay:start": { [_: string]: any };
            "recording:replay:stop": { [_: string]: any };
            "recording:start": { [_: string]: any };
            "recording:started": { [_: string]: any };
            "recording:stop": { [_: string]: any };
            "recording:stopped": { [_: string]: any };
            "ssh:hostkey_prompt": { [_: string]: any };
            "ssh:hostkey_response": { [_: string]: any };
            "ssh:known_hosts:delete": { [_: string]: any };
            "ssh:known_hosts:list": { [_: string]: any };
            "ssh:known_hosts:list:request": { [_: string]: any };
            "system:stats": main$0.SystemStats;
            "terminal:data": { [_: string]: any };
            "terminal:error": { [_: string]: any };
            "terminal:exit": { [_: string]: any };
        }
    }
}
