//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../term/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "ssh:hostkey_prompt": $$createType0,
        "ssh:hostkey_response": $$createType0,
        "ssh:known_hosts:delete": $$createType0,
        "ssh:known_hosts:list": $$createType0,
        "ssh:known_hosts:list:request": $$createType0,
        "system:stats": $$createType1,
        "terminal:data": $$createType0,
        "terminal:error": $$createType0,
        "terminal:exit": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = main$0.SystemStats.createFrom;

configure();
