// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../../../../io/models.js";

/**
 * Client implements a traditional SSH client that supports shells,
 * subprocesses, TCP port/streamlocal forwarding and tunneled dialing.
 */
export class Client {
    "Conn": Conn;

    /** Creates a new Client instance. */
    constructor($$source: Partial<Client> = {}) {
        if (!("Conn" in $$source)) {
            this["Conn"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     */
    static createFrom($$source: any = {}): Client {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Client($$parsedSource as Partial<Client>);
    }
}

/**
 * Conn represents an SSH connection for both server and client roles.
 * Conn is the basis for implementing an application layer, such
 * as ClientConn, which implements the traditional shell access for
 * clients.
 */
export type Conn = any;

/**
 * A Session represents a connection to a remote command or shell.
 */
export class Session {
    /**
     * Stdin specifies the remote process's standard input.
     * If Stdin is nil, the remote process reads from an empty
     * bytes.Buffer.
     */
    "Stdin": io$0.Reader;

    /**
     * Stdout and Stderr specify the remote process's standard
     * output and error.
     * 
     * If either is nil, Run connects the corresponding file
     * descriptor to an instance of io.Discard. There is a
     * fixed amount of buffering that is shared for the two streams.
     * If either blocks it may eventually cause the remote
     * command to block.
     */
    "Stdout": io$0.Writer;
    "Stderr": io$0.Writer;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("Stdin" in $$source)) {
            this["Stdin"] = null;
        }
        if (!("Stdout" in $$source)) {
            this["Stdout"] = null;
        }
        if (!("Stderr" in $$source)) {
            this["Stderr"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}
