// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum Handle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    InvalidHandle = 18446744073709551615,
};

export class SecurityAttributes {
    "Length": number;
    "SecurityDescriptor": number;
    "InheritHandle": number;

    /** Creates a new SecurityAttributes instance. */
    constructor($$source: Partial<SecurityAttributes> = {}) {
        if (!("Length" in $$source)) {
            this["Length"] = 0;
        }
        if (!("SecurityDescriptor" in $$source)) {
            this["SecurityDescriptor"] = 0;
        }
        if (!("InheritHandle" in $$source)) {
            this["InheritHandle"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityAttributes instance from a string or object.
     */
    static createFrom($$source: any = {}): SecurityAttributes {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecurityAttributes($$parsedSource as Partial<SecurityAttributes>);
    }
}

export class SysProcAttr {
    "HideWindow": boolean;

    /**
     * used if non-empty, else the windows command line is built by escaping the arguments passed to StartProcess
     */
    "CmdLine": string;
    "CreationFlags": number;

    /**
     * if set, runs new process in the security context represented by the token
     */
    "Token": Token;

    /**
     * if set, applies these security attributes as the descriptor for the new process
     */
    "ProcessAttributes": SecurityAttributes | null;

    /**
     * if set, applies these security attributes as the descriptor for the main thread of the new process
     */
    "ThreadAttributes": SecurityAttributes | null;

    /**
     * if set, no handles are inherited by the new process, not even the standard handles, contained in ProcAttr.Files, nor the ones contained in AdditionalInheritedHandles
     */
    "NoInheritHandles": boolean;

    /**
     * a list of additional handles, already marked as inheritable, that will be inherited by the new process
     */
    "AdditionalInheritedHandles": Handle[];

    /**
     * if non-zero, the new process regards the process given by this handle as its parent process, and AdditionalInheritedHandles, if set, should exist in this parent process
     */
    "ParentProcess": Handle;

    /** Creates a new SysProcAttr instance. */
    constructor($$source: Partial<SysProcAttr> = {}) {
        if (!("HideWindow" in $$source)) {
            this["HideWindow"] = false;
        }
        if (!("CmdLine" in $$source)) {
            this["CmdLine"] = "";
        }
        if (!("CreationFlags" in $$source)) {
            this["CreationFlags"] = 0;
        }
        if (!("Token" in $$source)) {
            this["Token"] = 0;
        }
        if (!("ProcessAttributes" in $$source)) {
            this["ProcessAttributes"] = null;
        }
        if (!("ThreadAttributes" in $$source)) {
            this["ThreadAttributes"] = null;
        }
        if (!("NoInheritHandles" in $$source)) {
            this["NoInheritHandles"] = false;
        }
        if (!("AdditionalInheritedHandles" in $$source)) {
            this["AdditionalInheritedHandles"] = [];
        }
        if (!("ParentProcess" in $$source)) {
            this["ParentProcess"] = Handle.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SysProcAttr instance from a string or object.
     */
    static createFrom($$source: any = {}): SysProcAttr {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ProcessAttributes" in $$parsedSource) {
            $$parsedSource["ProcessAttributes"] = $$createField4_0($$parsedSource["ProcessAttributes"]);
        }
        if ("ThreadAttributes" in $$parsedSource) {
            $$parsedSource["ThreadAttributes"] = $$createField5_0($$parsedSource["ThreadAttributes"]);
        }
        if ("AdditionalInheritedHandles" in $$parsedSource) {
            $$parsedSource["AdditionalInheritedHandles"] = $$createField7_0($$parsedSource["AdditionalInheritedHandles"]);
        }
        return new SysProcAttr($$parsedSource as Partial<SysProcAttr>);
    }
}

/**
 * An access token contains the security information for a logon session.
 * The system creates an access token when a user logs on, and every
 * process executed on behalf of the user has a copy of the token.
 * The token identifies the user, the user's groups, and the user's
 * privileges. The system uses the token to control access to securable
 * objects and to control the ability of the user to perform various
 * system-related operations on the local computer.
 */
export type Token = number;

// Private type creation functions
const $$createType0 = SecurityAttributes.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
