// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * File represents an open file descriptor.
 * 
 * The methods of File are safe for concurrent use.
 */
export class File {

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new File($$parsedSource as Partial<File>);
    }
}

/**
 * Process stores the information about a process created by [StartProcess].
 */
export class Process {
    "Pid": number;

    /** Creates a new Process instance. */
    constructor($$source: Partial<Process> = {}) {
        if (!("Pid" in $$source)) {
            this["Pid"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Process instance from a string or object.
     */
    static createFrom($$source: any = {}): Process {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Process($$parsedSource as Partial<Process>);
    }
}

/**
 * ProcessState stores information about a process, as reported by Wait.
 */
export class ProcessState {

    /** Creates a new ProcessState instance. */
    constructor($$source: Partial<ProcessState> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessState instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessState($$parsedSource as Partial<ProcessState>);
    }
}
