// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * SessionNode represents a node in the session tree (folder or session)
 */
export class SessionNode {
    "id": string;
    "parentId": string | null;
    "name": string;

    /**
     * "folder" or "session"
     */
    "type": string;

    /**
     * "ssh", "bash", etc.
     */
    "sessionType"?: string | null;
    "position": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new SessionNode instance. */
    constructor($$source: Partial<SessionNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionNode instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionNode($$parsedSource as Partial<SessionNode>);
    }
}

/**
 * Setting represents an application setting
 */
export class Setting {
    "key": string;
    "value": string;

    /**
     * "string", "int", "bool", "json"
     */
    "valueType": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Setting instance. */
    constructor($$source: Partial<Setting> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("valueType" in $$source)) {
            this["valueType"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     */
    static createFrom($$source: any = {}): Setting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting($$parsedSource as Partial<Setting>);
    }
}
