// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * SessionNode represents a node in the session tree (folder or session)
 */
export class SessionNode {
    /**
     * Creates a new SessionNode instance.
     * @param {Partial<SessionNode>} [$$source = {}] - The source object to create the SessionNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["parentId"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "folder" or "session"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * "ssh", "bash", etc.
             * @member
             * @type {string | null | undefined}
             */
            this["sessionType"] = undefined;
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionNode(/** @type {Partial<SessionNode>} */($$parsedSource));
    }
}

/**
 * Setting represents an application setting
 */
export class Setting {
    /**
     * Creates a new Setting instance.
     * @param {Partial<Setting>} [$$source = {}] - The source object to create the Setting.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("valueType" in $$source)) {
            /**
             * "string", "int", "bool", "json"
             * @member
             * @type {string}
             */
            this["valueType"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Setting}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting(/** @type {Partial<Setting>} */($$parsedSource));
    }
}
